### PR TITLE
Add Get a single gist and Get a specific revision of a gist APIs

### LINKED ISSUE #237: Implement Get a single gist API
Get a single gist API is not implemented
https://developer.github.com/v3/gists/#get-a-single-gist

### PR DESCRIPTION
**Pull request by aleksandr-vin**
- Add files property to domain.Gist

Closes #237

Signed-off-by: Aleksandr Vinokurov <aleksandr.vin@gmail.com>

### CODE REVIEW

**Comment by aleksandr-vin** [comment]
I've made progress with #238 also, please check #240 combined PR.

**Comment by juanpedromoreno** [comment]
@aleksandr-vin I guess this can be closed, correct? Thanks!

**Comment by aleksandr-vin** [comment]
Closed as everything was done in #240

**Comment by juanpedromoreno** [comment]
Thanks @aleksandr-vin!

**Pull request closed without merging**
