### PR TITLE
Bump sbt-org-policies to 0.8.7 to benefit from cats 1.0.0-RC1 & co

### PR DESCRIPTION
**Pull request by BenFradet**

### CODE REVIEW

**Comment by BenFradet** [comment]
Do you think a 0.17.0-M1 release would make sense?

**Comment by juanpedromoreno** [comment]
Yes, feel free to bump it up in this PR

**Comment by BenFradet** [comment]
@juanpedromoreno done :+1:

**Comment by BenFradet** [comment]
Thanks for the reviews, merged!

**Pull request merged**
