### PR TITLE
Bump Travis' Scala version to 2.12.4

### PR DESCRIPTION
**Pull request by BenFradet**

### CODE REVIEW

**Comment by fedefernandez** [comment]
@BenFradet I'm almost sure that sbt-org-policies doesn't work very well with versions like M1, RC1, etc. Would it be possible to rename the version in this PR to a final one?

**Comment by BenFradet** [comment]
@fedefernandez sure done :+1:

**Comment by fedefernandez** [comment]
:+1:

**Comment by BenFradet** [comment]
Thanks for the help, merged!

**Pull request merged**
