### PR TITLE
JP - Fetch Repo Contributors List

### PR DESCRIPTION
**Pull request by juanpedromoreno**
This PR brings the ability to fetch contributors from the specified repository.

Please, @dialelo @rafaparadela could you review? Thanks!

### CODE REVIEW

**Comment by rafaparadela** [comment]
LGTM, thanks

**Comment by dialelo** [comment]
LGTM :+1:

**Comment by dialelo** [comment]
Just published a `0.6-SNAPSHOT` release including these changes :shipit:

**Comment by juanpedromoreno** [comment]
Nice @dialelo !

**Pull request merged**
