### PR TITLE
Rafa 15 unit test

### LINKED ISSUE #15: Unit testing
Add more unit tests to improve the test coverage.

### PR DESCRIPTION
**Pull request by rafaparadela**
This PR fixes #15 . More details:

- Adds a mock server for unit testing.
- Adds a proper way to read config parameters
- Add unit tests for Users APIs
- Add unit tests for Repos APIs
- Add unit tests for Auth APIs

### CODE REVIEW

**Comment by rafaparadela** [comment]
@franciscodr Could you review please? Thank you

**Comment by franciscodr** [comment]
[LGTM](http://lgtm.in/i/GBkTtJUKs)
LGTM

**Comment by 47degdev** [comment]
this is the comment

**Comment by bond15** [comment]
this is the comment

**Comment by 47degdev** [comment]
this is the comment

**Comment by 47degdev** [comment]
this is the comment

**Comment by rafaparadela** [comment]
@bond15 Are we proving the API to add comments in PRs by using this one? If so... I need to unsubscribe from this thread :-)

**Comment by bond15** [comment]
this is the comment

**Pull request merged**
