### PR TITLE
update build

### PR DESCRIPTION
**Pull request by AdrianRaFo**
Update to sbt 1.0.x

### CODE REVIEW

**Comment by juanpedromoreno** [comment]
Looks good, but builds seem to be failing 🤔

**Comment by AdrianRaFo** [comment]
I try to run the tests in master and failed too, integrations test by the way, so it can be failing by the test repo, @juanpedromoreno can you confirm it?

**Comment by juanpedromoreno** [comment]
Mmm... It seems to be a binary incompatibility, I'd need to look at it deeper

**Comment by juanpedromoreno** [comment]
Is the current issue the same that you found last week, @suhasgaddam ?

**Comment by AdrianRaFo** [comment]
I'm going to mark this as blocked until the test library is fixed

**Comment by juanpedromoreno** [comment]
Could we go ahead keeping `0.13.16`?

**Comment by AdrianRaFo** [comment]
I can try but freestyle doesn't is for scala 2.10, It's ok if I remove that support?

**Comment by suhasgaddam** [comment]
@AdrianRaFo unless I missed a PR, github4s still supports 2.10 and has not switched to freestyle yet. The build project can use 0.13/2.10, and the "real" project can use any Scala version. (I think I am using bad wording with respect to build vs "real" project.)

**Comment by AdrianRaFo** [comment]
@suhasgaddam the purpose of my pr is to prepare github4s to make a freestyle migration

**Comment by BenFradet** [comment]
I'm 👍 on dropping 2.10

**Comment by suhasgaddam** [comment]
Ah, for some reason I thought it was only to bump sbt-org-policies. You can still make forward progress on converting to freestyle with keeping the sbt version to 0.13.16 and bumping sbt-org-policies.

It gets interesting because sbt-org-policies itself has a dependency on github4s(currently the cats 0.9 version due to another issue), but that dependency will not collide with the "real" project.

In terms of dropping 2.10(specifically the consequences for sbt-org-policies), I'll defer to @juanpedromoreno. We'll eventually stop publishing sbt-org-policies for 0.13.16, but I have no idea for that timeline.

**Comment by juanpedromoreno** [comment]
Let's close this since other PRs have upgraded the build.

**Comment by BenFradet** [comment]
unless I'm mistaken it's still on 0.13.x, no?

**Comment by juanpedromoreno** [comment]
Yeah, that's true. IMHO, let's do it after this release, potentially removing Scala 2.10 support.

**Pull request closed without merging**
